# Generated by Django 3.1.12 on 2024-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=255)),
                ('FECHA_SUBIDA', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
